LocalSocket /var/run/clamav/clamd.ctl
LocalSocketMode 666
FixStaleSocket yes

DatabaseDirectory /var/lib/clamav

# Логи
LogFile /var/log/clamav/clamav.log
LogTime yes
LogVerbose no

# Производительность
MaxThreads 4
MaxFileSize 25M
MaxScanSize 100M
MaxRecursion 16

User clamav
AllowSupplementaryGroups yes
